# ===================================
#  Reorder Behavior Config
# ===================================

# Model Class name
modelClass: Pensoft\CommunitiesPractice\Models\CommunitiesPractice

# Key column name to use for the sort order
orderColumn: sort_order

# Title to use for the reorder page
title: Reorder Demonstrations Projects

# The attribute on the model to use for the display name
nameFrom: slug